// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace WebApplication.Areas.admin.Controllers
{
    public partial class ManageController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ManageController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> UpdateProfile()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProfile);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> CompleteInformationUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CompleteInformationUser);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ProfileUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileUser);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CommentUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CommentUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PagedIndexComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PagedIndexComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DataSaleUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DataSaleUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PagedIndexSale()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PagedIndexSale);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SendMessage()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendMessage);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> DisableUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisableUser);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> DeleteUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SendEmail()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendEmail);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ManageController Actions { get { return MVC.admin.Manage; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Manage";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Manage";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Register = "Register";
            public readonly string UpdateProfile = "UpdateProfile";
            public readonly string serachUser = "serachUser";
            public readonly string DataUser = "DataUser";
            public readonly string CompleteInformationUser = "CompleteInformationUser";
            public readonly string ProfileUser = "ProfileUser";
            public readonly string CommentUser = "CommentUser";
            public readonly string PagedIndexComment = "PagedIndexComment";
            public readonly string DataSaleUser = "DataSaleUser";
            public readonly string PagedIndexSale = "PagedIndexSale";
            public readonly string SendMessage = "SendMessage";
            public readonly string DisableUser = "DisableUser";
            public readonly string DeleteUser = "DeleteUser";
            public readonly string SendEmail = "SendEmail";
            public readonly string SendSMS = "SendSMS";
            public readonly string LogOff = "LogOff";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Register = "Register";
            public const string UpdateProfile = "UpdateProfile";
            public const string serachUser = "serachUser";
            public const string DataUser = "DataUser";
            public const string CompleteInformationUser = "CompleteInformationUser";
            public const string ProfileUser = "ProfileUser";
            public const string CommentUser = "CommentUser";
            public const string PagedIndexComment = "PagedIndexComment";
            public const string DataSaleUser = "DataSaleUser";
            public const string PagedIndexSale = "PagedIndexSale";
            public const string SendMessage = "SendMessage";
            public const string DisableUser = "DisableUser";
            public const string DeleteUser = "DeleteUser";
            public const string SendEmail = "SendEmail";
            public const string SendSMS = "SendSMS";
            public const string LogOff = "LogOff";
        }


        static readonly ActionParamsClass_Register s_params_Register = new ActionParamsClass_Register();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Register RegisterParams { get { return s_params_Register; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Register
        {
            public readonly string userViewModel = "userViewModel";
            public readonly string SelectedRoles = "SelectedRoles";
        }
        static readonly ActionParamsClass_UpdateProfile s_params_UpdateProfile = new ActionParamsClass_UpdateProfile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateProfile UpdateProfileParams { get { return s_params_UpdateProfile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateProfile
        {
            public readonly string Id = "Id";
            public readonly string userProfile = "userProfile";
            public readonly string selectedRole = "selectedRole";
        }
        static readonly ActionParamsClass_DataUser s_params_DataUser = new ActionParamsClass_DataUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DataUser DataUserParams { get { return s_params_DataUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DataUser
        {
            public readonly string term = "term";
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_CompleteInformationUser s_params_CompleteInformationUser = new ActionParamsClass_CompleteInformationUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CompleteInformationUser CompleteInformationUserParams { get { return s_params_CompleteInformationUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CompleteInformationUser
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_ProfileUser s_params_ProfileUser = new ActionParamsClass_ProfileUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProfileUser ProfileUserParams { get { return s_params_ProfileUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProfileUser
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_CommentUser s_params_CommentUser = new ActionParamsClass_CommentUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CommentUser CommentUserParams { get { return s_params_CommentUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CommentUser
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_PagedIndexComment s_params_PagedIndexComment = new ActionParamsClass_PagedIndexComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PagedIndexComment PagedIndexCommentParams { get { return s_params_PagedIndexComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PagedIndexComment
        {
            public readonly string page = "page";
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_DataSaleUser s_params_DataSaleUser = new ActionParamsClass_DataSaleUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DataSaleUser DataSaleUserParams { get { return s_params_DataSaleUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DataSaleUser
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_PagedIndexSale s_params_PagedIndexSale = new ActionParamsClass_PagedIndexSale();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PagedIndexSale PagedIndexSaleParams { get { return s_params_PagedIndexSale; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PagedIndexSale
        {
            public readonly string page = "page";
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_SendMessage s_params_SendMessage = new ActionParamsClass_SendMessage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendMessage SendMessageParams { get { return s_params_SendMessage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendMessage
        {
            public readonly string Id = "Id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DisableUser s_params_DisableUser = new ActionParamsClass_DisableUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DisableUser DisableUserParams { get { return s_params_DisableUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DisableUser
        {
            public readonly string Id = "Id";
            public readonly string disableUser = "disableUser";
        }
        static readonly ActionParamsClass_DeleteUser s_params_DeleteUser = new ActionParamsClass_DeleteUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUser DeleteUserParams { get { return s_params_DeleteUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUser
        {
            public readonly string Id = "Id";
            public readonly string deleteUser = "deleteUser";
        }
        static readonly ActionParamsClass_SendEmail s_params_SendEmail = new ActionParamsClass_SendEmail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendEmail SendEmailParams { get { return s_params_SendEmail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendEmail
        {
            public readonly string Id = "Id";
            public readonly string sendEmail = "sendEmail";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _DataCommentUser = "_DataCommentUser";
                public readonly string _DataSale = "_DataSale";
                public readonly string _DataUser = "_DataUser";
                public readonly string _DeleteUser = "_DeleteUser";
                public readonly string _DisableUser = "_DisableUser";
                public readonly string _FavoriteListUser = "_FavoriteListUser";
                public readonly string _IndexDataComment = "_IndexDataComment";
                public readonly string _IndexDataSale = "_IndexDataSale";
                public readonly string _ProfileUser = "_ProfileUser";
                public readonly string _searchUser = "_searchUser";
                public readonly string _SendEmail = "_SendEmail";
                public readonly string _SendMessage = "_SendMessage";
                public readonly string _SidebarUser = "_SidebarUser";
                public readonly string _solidHeaderUser = "_solidHeaderUser";
                public readonly string _UpdateProfile = "_UpdateProfile";
                public readonly string CompleteInformationUser = "CompleteInformationUser";
                public readonly string Index = "Index";
                public readonly string Register = "Register";
            }
            public readonly string _DataCommentUser = "~/Areas/admin/Views/Manage/_DataCommentUser.cshtml";
            public readonly string _DataSale = "~/Areas/admin/Views/Manage/_DataSale.cshtml";
            public readonly string _DataUser = "~/Areas/admin/Views/Manage/_DataUser.cshtml";
            public readonly string _DeleteUser = "~/Areas/admin/Views/Manage/_DeleteUser.cshtml";
            public readonly string _DisableUser = "~/Areas/admin/Views/Manage/_DisableUser.cshtml";
            public readonly string _FavoriteListUser = "~/Areas/admin/Views/Manage/_FavoriteListUser.cshtml";
            public readonly string _IndexDataComment = "~/Areas/admin/Views/Manage/_IndexDataComment.cshtml";
            public readonly string _IndexDataSale = "~/Areas/admin/Views/Manage/_IndexDataSale.cshtml";
            public readonly string _ProfileUser = "~/Areas/admin/Views/Manage/_ProfileUser.cshtml";
            public readonly string _searchUser = "~/Areas/admin/Views/Manage/_searchUser.cshtml";
            public readonly string _SendEmail = "~/Areas/admin/Views/Manage/_SendEmail.cshtml";
            public readonly string _SendMessage = "~/Areas/admin/Views/Manage/_SendMessage.cshtml";
            public readonly string _SidebarUser = "~/Areas/admin/Views/Manage/_SidebarUser.cshtml";
            public readonly string _solidHeaderUser = "~/Areas/admin/Views/Manage/_solidHeaderUser.cshtml";
            public readonly string _UpdateProfile = "~/Areas/admin/Views/Manage/_UpdateProfile.cshtml";
            public readonly string CompleteInformationUser = "~/Areas/admin/Views/Manage/CompleteInformationUser.cshtml";
            public readonly string Index = "~/Areas/admin/Views/Manage/Index.cshtml";
            public readonly string Register = "~/Areas/admin/Views/Manage/Register.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ManageController : WebApplication.Areas.admin.Controllers.ManageController
    {
        public T4MVC_ManageController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Register()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            RegisterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, WebApplication.ViewModels.RegisterViewModel userViewModel, string[] SelectedRoles);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Register(WebApplication.ViewModels.RegisterViewModel userViewModel, string[] SelectedRoles)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userViewModel", userViewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "SelectedRoles", SelectedRoles);
            RegisterOverride(callInfo, userViewModel, SelectedRoles);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void UpdateProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? Id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> UpdateProfile(int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProfile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            UpdateProfileOverride(callInfo, Id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void UpdateProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.ViewModelClasses.UpdateProfileUserViewModel userProfile, string[] selectedRole);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> UpdateProfile(eShop.WebApplication.DomainClasses.ViewModelClasses.UpdateProfileUserViewModel userProfile, string[] selectedRole)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProfile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userProfile", userProfile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "selectedRole", selectedRole);
            UpdateProfileOverride(callInfo, userProfile, selectedRole);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void serachUserOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult serachUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.serachUser);
            serachUserOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DataUserOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string term, int page, int count);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DataUser(string term, int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DataUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            DataUserOverride(callInfo, term, page, count);
            return callInfo;
        }

        [NonAction]
        partial void CompleteInformationUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? Id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> CompleteInformationUser(int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CompleteInformationUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            CompleteInformationUserOverride(callInfo, Id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void ProfileUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ProfileUser(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ProfileUserOverride(callInfo, Id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void UpdateProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> UpdateProfile(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProfile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            UpdateProfileOverride(callInfo, Id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void CommentUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult CommentUser(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CommentUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            CommentUserOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void PagedIndexCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PagedIndexComment(int? page, int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PagedIndexComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            PagedIndexCommentOverride(callInfo, page, Id);
            return callInfo;
        }

        [NonAction]
        partial void DataSaleUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DataSaleUser(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DataSaleUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DataSaleUserOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void PagedIndexSaleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PagedIndexSale(int? page, int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PagedIndexSale);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            PagedIndexSaleOverride(callInfo, page, Id);
            return callInfo;
        }

        [NonAction]
        partial void SendMessageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SendMessage(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendMessage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            SendMessageOverride(callInfo, Id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void SendMessageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.IdentityViewModel.SendSMSProfileViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendMessage(eShop.WebApplication.DomainClasses.IdentityViewModel.SendSMSProfileViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendMessage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SendMessageOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DisableUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> DisableUser(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisableUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DisableUserOverride(callInfo, Id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void DisableUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.ViewModelClasses.DisableUserViewModel disableUser);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> DisableUser(eShop.WebApplication.DomainClasses.ViewModelClasses.DisableUserViewModel disableUser)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisableUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "disableUser", disableUser);
            DisableUserOverride(callInfo, disableUser);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void DeleteUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> DeleteUser(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteUserOverride(callInfo, Id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void DeleteUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.ViewModelClasses.DeleteUserProfileViewModel deleteUser);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> DeleteUser(eShop.WebApplication.DomainClasses.ViewModelClasses.DeleteUserProfileViewModel deleteUser)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deleteUser", deleteUser);
            DeleteUserOverride(callInfo, deleteUser);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void SendEmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SendEmail(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendEmail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            SendEmailOverride(callInfo, Id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void SendEmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.IdentityViewModel.SendEmailProfileViewModel sendEmail);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SendEmail(eShop.WebApplication.DomainClasses.IdentityViewModel.SendEmailProfileViewModel sendEmail)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendEmail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sendEmail", sendEmail);
            SendEmailOverride(callInfo, sendEmail);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void SendSMSOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SendSMS()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendSMS);
            SendSMSOverride(callInfo);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void LogOffOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogOff()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOff);
            LogOffOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
