// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace WebApplication.Areas.admin.Controllers
{
    public partial class SliderController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SliderController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SliderController Actions { get { return MVC.admin.Slider; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Slider";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Slider";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string CreateSlider = "CreateSlider";
            public readonly string DeleteImageSlider = "DeleteImageSlider";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string CreateSlider = "CreateSlider";
            public const string DeleteImageSlider = "DeleteImageSlider";
        }


        static readonly ActionParamsClass_DeleteImageSlider s_params_DeleteImageSlider = new ActionParamsClass_DeleteImageSlider();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteImageSlider DeleteImageSliderParams { get { return s_params_DeleteImageSlider; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteImageSlider
        {
            public readonly string checkboxImage = "checkboxImage";
        }
        static readonly ActionParamsClass_CreateSlider s_params_CreateSlider = new ActionParamsClass_CreateSlider();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateSlider CreateSliderParams { get { return s_params_CreateSlider; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateSlider
        {
            public readonly string sliderViewModel = "sliderViewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _SolidHeaderSlider = "_SolidHeaderSlider";
                public readonly string CreateSlider = "CreateSlider";
                public readonly string DeleteImageSlider = "DeleteImageSlider";
                public readonly string Index = "Index";
            }
            public readonly string _SolidHeaderSlider = "~/Areas/admin/Views/Slider/_SolidHeaderSlider.cshtml";
            public readonly string CreateSlider = "~/Areas/admin/Views/Slider/CreateSlider.cshtml";
            public readonly string DeleteImageSlider = "~/Areas/admin/Views/Slider/DeleteImageSlider.cshtml";
            public readonly string Index = "~/Areas/admin/Views/Slider/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SliderController : WebApplication.Areas.admin.Controllers.SliderController
    {
        public T4MVC_SliderController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateSliderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateSlider()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateSlider);
            CreateSliderOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DeleteImageSliderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteImageSlider()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteImageSlider);
            DeleteImageSliderOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DeleteImageSliderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<string> checkboxImage);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteImageSlider(System.Collections.Generic.List<string> checkboxImage)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteImageSlider);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "checkboxImage", checkboxImage);
            DeleteImageSliderOverride(callInfo, checkboxImage);
            return callInfo;
        }

        [NonAction]
        partial void CreateSliderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.ViewModelClasses.ShowSliderViewModel sliderViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateSlider(eShop.WebApplication.DomainClasses.ViewModelClasses.ShowSliderViewModel sliderViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateSlider);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sliderViewModel", sliderViewModel);
            CreateSliderOverride(callInfo, sliderViewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
