// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace WebApplication.Areas.admin.Controllers
{
    public partial class PackageController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PackageController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CalculatedUltimated()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CalculatedUltimated);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult UploadFiles()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UploadFiles);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PagedIndex()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PagedIndex);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Calculated_discount_atFirst()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Calculated_discount_atFirst);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DataPackage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DataPackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DetailsDataPackage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailsDataPackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LoadProductPerPackage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadProductPerPackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdatePackage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdatePackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddProductPackage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProductPackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LoadOtherProductToPackage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadOtherProductToPackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult DeleteProductPerPackage()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DeleteProductPerPackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult SubmitAddOtherProductToPackage()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SubmitAddOtherProductToPackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteProductPackage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteProductPackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult SubmitDeleteProductPerPackage()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SubmitDeleteProductPerPackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeletePackage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePackage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CheckNameEdit()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckNameEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CheckName()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckName);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PackageController Actions { get { return MVC.admin.Package; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Package";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Package";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string CreatePackage = "CreatePackage";
            public readonly string CalculatedUltimated = "CalculatedUltimated";
            public readonly string UploadFiles = "UploadFiles";
            public readonly string PagedIndex = "PagedIndex";
            public readonly string Calculated_discount_atFirst = "Calculated_discount_atFirst";
            public readonly string DataPackage = "DataPackage";
            public readonly string DetailsDataPackage = "DetailsDataPackage";
            public readonly string LoadProductPerPackage = "LoadProductPerPackage";
            public readonly string UpdatePackage = "UpdatePackage";
            public readonly string AddProductPackage = "AddProductPackage";
            public readonly string LoadOtherProductToPackage = "LoadOtherProductToPackage";
            public readonly string DeleteProductPerPackage = "DeleteProductPerPackage";
            public readonly string SubmitAddOtherProductToPackage = "SubmitAddOtherProductToPackage";
            public readonly string DeleteProductPackage = "DeleteProductPackage";
            public readonly string SubmitDeleteProductPerPackage = "SubmitDeleteProductPerPackage";
            public readonly string DeletePackage = "DeletePackage";
            public readonly string CheckNameEdit = "CheckNameEdit";
            public readonly string CheckName = "CheckName";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string CreatePackage = "CreatePackage";
            public const string CalculatedUltimated = "CalculatedUltimated";
            public const string UploadFiles = "UploadFiles";
            public const string PagedIndex = "PagedIndex";
            public const string Calculated_discount_atFirst = "Calculated_discount_atFirst";
            public const string DataPackage = "DataPackage";
            public const string DetailsDataPackage = "DetailsDataPackage";
            public const string LoadProductPerPackage = "LoadProductPerPackage";
            public const string UpdatePackage = "UpdatePackage";
            public const string AddProductPackage = "AddProductPackage";
            public const string LoadOtherProductToPackage = "LoadOtherProductToPackage";
            public const string DeleteProductPerPackage = "DeleteProductPerPackage";
            public const string SubmitAddOtherProductToPackage = "SubmitAddOtherProductToPackage";
            public const string DeleteProductPackage = "DeleteProductPackage";
            public const string SubmitDeleteProductPerPackage = "SubmitDeleteProductPerPackage";
            public const string DeletePackage = "DeletePackage";
            public const string CheckNameEdit = "CheckNameEdit";
            public const string CheckName = "CheckName";
        }


        static readonly ActionParamsClass_CalculatedUltimated s_params_CalculatedUltimated = new ActionParamsClass_CalculatedUltimated();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CalculatedUltimated CalculatedUltimatedParams { get { return s_params_CalculatedUltimated; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CalculatedUltimated
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_UploadFiles s_params_UploadFiles = new ActionParamsClass_UploadFiles();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadFiles UploadFilesParams { get { return s_params_UploadFiles; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadFiles
        {
            public readonly string controlUpload = "controlUpload";
            public readonly string id = "id";
            public readonly string array = "array";
            public readonly string isShow = "isShow";
            public readonly string SubCategory_Id = "SubCategory_Id";
        }
        static readonly ActionParamsClass_PagedIndex s_params_PagedIndex = new ActionParamsClass_PagedIndex();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PagedIndex PagedIndexParams { get { return s_params_PagedIndex; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PagedIndex
        {
            public readonly string page = "page";
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_Calculated_discount_atFirst s_params_Calculated_discount_atFirst = new ActionParamsClass_Calculated_discount_atFirst();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Calculated_discount_atFirst Calculated_discount_atFirstParams { get { return s_params_Calculated_discount_atFirst; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Calculated_discount_atFirst
        {
            public readonly string ProductId = "ProductId";
            public readonly string disCount = "disCount";
        }
        static readonly ActionParamsClass_DataPackage s_params_DataPackage = new ActionParamsClass_DataPackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DataPackage DataPackageParams { get { return s_params_DataPackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DataPackage
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_DetailsDataPackage s_params_DetailsDataPackage = new ActionParamsClass_DetailsDataPackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailsDataPackage DetailsDataPackageParams { get { return s_params_DetailsDataPackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailsDataPackage
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_LoadProductPerPackage s_params_LoadProductPerPackage = new ActionParamsClass_LoadProductPerPackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadProductPerPackage LoadProductPerPackageParams { get { return s_params_LoadProductPerPackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadProductPerPackage
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_UpdatePackage s_params_UpdatePackage = new ActionParamsClass_UpdatePackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdatePackage UpdatePackageParams { get { return s_params_UpdatePackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdatePackage
        {
            public readonly string Id = "Id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddProductPackage s_params_AddProductPackage = new ActionParamsClass_AddProductPackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddProductPackage AddProductPackageParams { get { return s_params_AddProductPackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddProductPackage
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_LoadOtherProductToPackage s_params_LoadOtherProductToPackage = new ActionParamsClass_LoadOtherProductToPackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadOtherProductToPackage LoadOtherProductToPackageParams { get { return s_params_LoadOtherProductToPackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadOtherProductToPackage
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_DeleteProductPerPackage s_params_DeleteProductPerPackage = new ActionParamsClass_DeleteProductPerPackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteProductPerPackage DeleteProductPerPackageParams { get { return s_params_DeleteProductPerPackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteProductPerPackage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SubmitAddOtherProductToPackage s_params_SubmitAddOtherProductToPackage = new ActionParamsClass_SubmitAddOtherProductToPackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SubmitAddOtherProductToPackage SubmitAddOtherProductToPackageParams { get { return s_params_SubmitAddOtherProductToPackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SubmitAddOtherProductToPackage
        {
            public readonly string Package_Id = "Package_Id";
            public readonly string array = "array";
        }
        static readonly ActionParamsClass_DeleteProductPackage s_params_DeleteProductPackage = new ActionParamsClass_DeleteProductPackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteProductPackage DeleteProductPackageParams { get { return s_params_DeleteProductPackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteProductPackage
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_SubmitDeleteProductPerPackage s_params_SubmitDeleteProductPerPackage = new ActionParamsClass_SubmitDeleteProductPerPackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SubmitDeleteProductPerPackage SubmitDeleteProductPerPackageParams { get { return s_params_SubmitDeleteProductPerPackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SubmitDeleteProductPerPackage
        {
            public readonly string Package_Id = "Package_Id";
            public readonly string array = "array";
        }
        static readonly ActionParamsClass_DeletePackage s_params_DeletePackage = new ActionParamsClass_DeletePackage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeletePackage DeletePackageParams { get { return s_params_DeletePackage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeletePackage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CheckNameEdit s_params_CheckNameEdit = new ActionParamsClass_CheckNameEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckNameEdit CheckNameEditParams { get { return s_params_CheckNameEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckNameEdit
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CheckName s_params_CheckName = new ActionParamsClass_CheckName();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckName CheckNameParams { get { return s_params_CheckName; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckName
        {
            public readonly string name = "name";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _BaseInformationPackage = "_BaseInformationPackage";
                public readonly string _DataPackage = "_DataPackage";
                public readonly string _DataShowPackage = "_DataShowPackage";
                public readonly string _DetailsHeaderPackageInformation = "_DetailsHeaderPackageInformation";
                public readonly string _SolidHeaderAddProductPackage = "_SolidHeaderAddProductPackage";
                public readonly string _SolidHeaderCreatePackage = "_SolidHeaderCreatePackage";
                public readonly string _SolidHeaderPackage = "_SolidHeaderPackage";
                public readonly string AddProductPackage = "AddProductPackage";
                public readonly string CreatePackage = "CreatePackage";
                public readonly string DeleteProductPackage = "DeleteProductPackage";
                public readonly string DetailsDataPackage = "DetailsDataPackage";
                public readonly string Index = "Index";
                public readonly string LoadProductPerPackage = "LoadProductPerPackage";
                public readonly string packageinfo = "packageinfo";
                public readonly string UpdatePackage = "UpdatePackage";
            }
            public readonly string _BaseInformationPackage = "~/Areas/admin/Views/Package/_BaseInformationPackage.cshtml";
            public readonly string _DataPackage = "~/Areas/admin/Views/Package/_DataPackage.cshtml";
            public readonly string _DataShowPackage = "~/Areas/admin/Views/Package/_DataShowPackage.cshtml";
            public readonly string _DetailsHeaderPackageInformation = "~/Areas/admin/Views/Package/_DetailsHeaderPackageInformation.cshtml";
            public readonly string _SolidHeaderAddProductPackage = "~/Areas/admin/Views/Package/_SolidHeaderAddProductPackage.cshtml";
            public readonly string _SolidHeaderCreatePackage = "~/Areas/admin/Views/Package/_SolidHeaderCreatePackage.cshtml";
            public readonly string _SolidHeaderPackage = "~/Areas/admin/Views/Package/_SolidHeaderPackage.cshtml";
            public readonly string AddProductPackage = "~/Areas/admin/Views/Package/AddProductPackage.cshtml";
            public readonly string CreatePackage = "~/Areas/admin/Views/Package/CreatePackage.cshtml";
            public readonly string DeleteProductPackage = "~/Areas/admin/Views/Package/DeleteProductPackage.cshtml";
            public readonly string DetailsDataPackage = "~/Areas/admin/Views/Package/DetailsDataPackage.cshtml";
            public readonly string Index = "~/Areas/admin/Views/Package/Index.cshtml";
            public readonly string LoadProductPerPackage = "~/Areas/admin/Views/Package/LoadProductPerPackage.cshtml";
            public readonly string packageinfo = "~/Areas/admin/Views/Package/packageinfo.txt";
            public readonly string UpdatePackage = "~/Areas/admin/Views/Package/UpdatePackage.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PackageController : WebApplication.Areas.admin.Controllers.PackageController
    {
        public T4MVC_PackageController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreatePackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreatePackage()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreatePackage);
            CreatePackageOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CalculatedUltimatedOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, WebApplication.ViewModels.PackageAddViewModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult CalculatedUltimated(WebApplication.ViewModels.PackageAddViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CalculatedUltimated);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CalculatedUltimatedOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void UploadFilesOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, System.Web.HttpPostedFileBase controlUpload, int id, string array, bool isShow, int SubCategory_Id);

        [NonAction]
        public override System.Web.Mvc.JsonResult UploadFiles(System.Web.HttpPostedFileBase controlUpload, int id, string array, bool isShow, int SubCategory_Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UploadFiles);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controlUpload", controlUpload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "array", array);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isShow", isShow);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "SubCategory_Id", SubCategory_Id);
            UploadFilesOverride(callInfo, controlUpload, id, array, isShow, SubCategory_Id);
            return callInfo;
        }

        [NonAction]
        partial void PagedIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PagedIndex(int? page, int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PagedIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            PagedIndexOverride(callInfo, page, Id);
            return callInfo;
        }

        [NonAction]
        partial void Calculated_discount_atFirstOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int[] ProductId, int disCount);

        [NonAction]
        public override System.Web.Mvc.JsonResult Calculated_discount_atFirst(int[] ProductId, int disCount)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Calculated_discount_atFirst);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ProductId", ProductId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "disCount", disCount);
            Calculated_discount_atFirstOverride(callInfo, ProductId, disCount);
            return callInfo;
        }

        [NonAction]
        partial void DataPackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page);

        [NonAction]
        public override System.Web.Mvc.ActionResult DataPackage(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DataPackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            DataPackageOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void DetailsDataPackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetailsDataPackage(int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailsDataPackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DetailsDataPackageOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void LoadProductPerPackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadProductPerPackage(int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadProductPerPackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            LoadProductPerPackageOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void UpdatePackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdatePackage(int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdatePackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            UpdatePackageOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void UpdatePackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, WebApplication.ViewModels.PackageEditViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdatePackage(WebApplication.ViewModels.PackageEditViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdatePackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            UpdatePackageOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void AddProductPackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddProductPackage(int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProductPackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            AddProductPackageOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void LoadOtherProductToPackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadOtherProductToPackage(int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadOtherProductToPackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            LoadOtherProductToPackageOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteProductPerPackageOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DeleteProductPerPackage(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DeleteProductPerPackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteProductPerPackageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SubmitAddOtherProductToPackageOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int Package_Id, string array);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult SubmitAddOtherProductToPackage(int Package_Id, string array)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SubmitAddOtherProductToPackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Package_Id", Package_Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "array", array);
            SubmitAddOtherProductToPackageOverride(callInfo, Package_Id, array);
            return callInfo;
        }

        [NonAction]
        partial void DeleteProductPackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteProductPackage(int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteProductPackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteProductPackageOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void SubmitDeleteProductPerPackageOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int Package_Id, string array);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult SubmitDeleteProductPerPackage(int Package_Id, string array)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SubmitDeleteProductPerPackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Package_Id", Package_Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "array", array);
            SubmitDeleteProductPerPackageOverride(callInfo, Package_Id, array);
            return callInfo;
        }

        [NonAction]
        partial void DeletePackageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeletePackage(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePackage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeletePackageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CheckNameEditOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, eShop.WebApplication.DomainClasses.MainViewModel.ExistNamePackage model);

        [NonAction]
        public override System.Web.Mvc.JsonResult CheckNameEdit(eShop.WebApplication.DomainClasses.MainViewModel.ExistNamePackage model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckNameEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CheckNameEditOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CheckNameOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string name);

        [NonAction]
        public override System.Web.Mvc.JsonResult CheckName(string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            CheckNameOverride(callInfo, name);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
