// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace WebApplication.Areas.admin.Controllers
{
    public partial class SettingController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SettingController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult ComputeAndDeleteElmah()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ComputeAndDeleteElmah);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeleteIPDanger()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteIPDanger);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DetailsIPDanger()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailsIPDanger);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SendSimpleSMS2()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendSimpleSMS2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult dataSMSInfo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.dataSMSInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult dataSMSInfoRead()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.dataSMSInfoRead);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIPForAutoComplete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIPForAutoComplete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SettingController Actions { get { return MVC.admin.Setting; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Setting";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Setting";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ReadElmahException = "ReadElmahException";
            public readonly string ComputeAndDeleteElmah = "ComputeAndDeleteElmah";
            public readonly string IndexIPDanger = "IndexIPDanger";
            public readonly string DataIPDanger = "DataIPDanger";
            public readonly string SerachIPDanger = "SerachIPDanger";
            public readonly string DeleteIPDanger = "DeleteIPDanger";
            public readonly string DetailsIPDanger = "DetailsIPDanger";
            public readonly string ServiceSMS = "ServiceSMS";
            public readonly string getInfoAccount = "getInfoAccount";
            public readonly string SendSimpleSMS2 = "SendSimpleSMS2";
            public readonly string GetUnReadSMS = "GetUnReadSMS";
            public readonly string dataSMSInfo = "dataSMSInfo";
            public readonly string GetReadSMS = "GetReadSMS";
            public readonly string dataSMSInfoRead = "dataSMSInfoRead";
            public readonly string SchedulerList = "SchedulerList";
            public readonly string GetIPForAutoComplete = "GetIPForAutoComplete";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ReadElmahException = "ReadElmahException";
            public const string ComputeAndDeleteElmah = "ComputeAndDeleteElmah";
            public const string IndexIPDanger = "IndexIPDanger";
            public const string DataIPDanger = "DataIPDanger";
            public const string SerachIPDanger = "SerachIPDanger";
            public const string DeleteIPDanger = "DeleteIPDanger";
            public const string DetailsIPDanger = "DetailsIPDanger";
            public const string ServiceSMS = "ServiceSMS";
            public const string getInfoAccount = "getInfoAccount";
            public const string SendSimpleSMS2 = "SendSimpleSMS2";
            public const string GetUnReadSMS = "GetUnReadSMS";
            public const string dataSMSInfo = "dataSMSInfo";
            public const string GetReadSMS = "GetReadSMS";
            public const string dataSMSInfoRead = "dataSMSInfoRead";
            public const string SchedulerList = "SchedulerList";
            public const string GetIPForAutoComplete = "GetIPForAutoComplete";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string checkboxImage = "checkboxImage";
        }
        static readonly ActionParamsClass_ComputeAndDeleteElmah s_params_ComputeAndDeleteElmah = new ActionParamsClass_ComputeAndDeleteElmah();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ComputeAndDeleteElmah ComputeAndDeleteElmahParams { get { return s_params_ComputeAndDeleteElmah; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ComputeAndDeleteElmah
        {
            public readonly string dictinaryViewModels = "dictinaryViewModels";
        }
        static readonly ActionParamsClass_DataIPDanger s_params_DataIPDanger = new ActionParamsClass_DataIPDanger();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DataIPDanger DataIPDangerParams { get { return s_params_DataIPDanger; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DataIPDanger
        {
            public readonly string term = "term";
            public readonly string count = "count";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_DeleteIPDanger s_params_DeleteIPDanger = new ActionParamsClass_DeleteIPDanger();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteIPDanger DeleteIPDangerParams { get { return s_params_DeleteIPDanger; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteIPDanger
        {
            public readonly string Id = "Id";
            public readonly string IPAddress = "IPAddress";
        }
        static readonly ActionParamsClass_DetailsIPDanger s_params_DetailsIPDanger = new ActionParamsClass_DetailsIPDanger();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailsIPDanger DetailsIPDangerParams { get { return s_params_DetailsIPDanger; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailsIPDanger
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_SendSimpleSMS2 s_params_SendSimpleSMS2 = new ActionParamsClass_SendSimpleSMS2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendSimpleSMS2 SendSimpleSMS2Params { get { return s_params_SendSimpleSMS2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendSimpleSMS2
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_dataSMSInfo s_params_dataSMSInfo = new ActionParamsClass_dataSMSInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_dataSMSInfo dataSMSInfoParams { get { return s_params_dataSMSInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_dataSMSInfo
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_dataSMSInfoRead s_params_dataSMSInfoRead = new ActionParamsClass_dataSMSInfoRead();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_dataSMSInfoRead dataSMSInfoReadParams { get { return s_params_dataSMSInfoRead; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_dataSMSInfoRead
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_GetIPForAutoComplete s_params_GetIPForAutoComplete = new ActionParamsClass_GetIPForAutoComplete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIPForAutoComplete GetIPForAutoCompleteParams { get { return s_params_GetIPForAutoComplete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIPForAutoComplete
        {
            public readonly string term = "term";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _DataElmah = "_DataElmah";
                public readonly string _DataIPDanger = "_DataIPDanger";
                public readonly string _dataSMS = "_dataSMS";
                public readonly string _DetailsAccountSMS = "_DetailsAccountSMS";
                public readonly string _SearchIPDanger = "_SearchIPDanger";
                public readonly string _SolidHeaderDetailsIPDanger = "_SolidHeaderDetailsIPDanger";
                public readonly string _solidHeaderElmah = "_solidHeaderElmah";
                public readonly string _SolidHeaderIPDanger = "_SolidHeaderIPDanger";
                public readonly string _SolidHeaderScheduler = "_SolidHeaderScheduler";
                public readonly string DetailsIPDanger = "DetailsIPDanger";
                public readonly string GetReadSMS = "GetReadSMS";
                public readonly string GetUnReadSMS = "GetUnReadSMS";
                public readonly string Index = "Index";
                public readonly string IndexIPDanger = "IndexIPDanger";
                public readonly string SchedulerList = "SchedulerList";
                public readonly string ServiceSMS = "ServiceSMS";
            }
            public readonly string _DataElmah = "~/Areas/admin/Views/Setting/_DataElmah.cshtml";
            public readonly string _DataIPDanger = "~/Areas/admin/Views/Setting/_DataIPDanger.cshtml";
            public readonly string _dataSMS = "~/Areas/admin/Views/Setting/_dataSMS.cshtml";
            public readonly string _DetailsAccountSMS = "~/Areas/admin/Views/Setting/_DetailsAccountSMS.cshtml";
            public readonly string _SearchIPDanger = "~/Areas/admin/Views/Setting/_SearchIPDanger.cshtml";
            public readonly string _SolidHeaderDetailsIPDanger = "~/Areas/admin/Views/Setting/_SolidHeaderDetailsIPDanger.cshtml";
            public readonly string _solidHeaderElmah = "~/Areas/admin/Views/Setting/_solidHeaderElmah.cshtml";
            public readonly string _SolidHeaderIPDanger = "~/Areas/admin/Views/Setting/_SolidHeaderIPDanger.cshtml";
            public readonly string _SolidHeaderScheduler = "~/Areas/admin/Views/Setting/_SolidHeaderScheduler.cshtml";
            public readonly string DetailsIPDanger = "~/Areas/admin/Views/Setting/DetailsIPDanger.cshtml";
            public readonly string GetReadSMS = "~/Areas/admin/Views/Setting/GetReadSMS.cshtml";
            public readonly string GetUnReadSMS = "~/Areas/admin/Views/Setting/GetUnReadSMS.cshtml";
            public readonly string Index = "~/Areas/admin/Views/Setting/Index.cshtml";
            public readonly string IndexIPDanger = "~/Areas/admin/Views/Setting/IndexIPDanger.cshtml";
            public readonly string SchedulerList = "~/Areas/admin/Views/Setting/SchedulerList.cshtml";
            public readonly string ServiceSMS = "~/Areas/admin/Views/Setting/ServiceSMS.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SettingController : WebApplication.Areas.admin.Controllers.SettingController
    {
        public T4MVC_SettingController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<string> checkboxImage);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(System.Collections.Generic.List<string> checkboxImage)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "checkboxImage", checkboxImage);
            IndexOverride(callInfo, checkboxImage);
            return callInfo;
        }

        [NonAction]
        partial void ReadElmahExceptionOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ReadElmahException()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ReadElmahException);
            ReadElmahExceptionOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ComputeAndDeleteElmahOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, System.Collections.Generic.IDictionary<string,eShop.WebApplication.DomainClasses.OtherViewModel.ElmahViewModel> dictinaryViewModels);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ComputeAndDeleteElmah(System.Collections.Generic.IDictionary<string,eShop.WebApplication.DomainClasses.OtherViewModel.ElmahViewModel> dictinaryViewModels)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ComputeAndDeleteElmah);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dictinaryViewModels", dictinaryViewModels);
            ComputeAndDeleteElmahOverride(callInfo, dictinaryViewModels);
            return callInfo;
        }

        [NonAction]
        partial void IndexIPDangerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult IndexIPDanger()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IndexIPDanger);
            IndexIPDangerOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DataIPDangerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term, int count, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult DataIPDanger(string term, int count, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DataIPDanger);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            DataIPDangerOverride(callInfo, term, count, page);
            return callInfo;
        }

        [NonAction]
        partial void SerachIPDangerOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult SerachIPDanger()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SerachIPDanger);
            SerachIPDangerOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DeleteIPDangerOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeleteIPDanger(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteIPDanger);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteIPDangerOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void DetailsIPDangerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetailsIPDanger(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailsIPDanger);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DetailsIPDangerOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteIPDangerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string IPAddress);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteIPDanger(string IPAddress)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteIPDanger);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "IPAddress", IPAddress);
            DeleteIPDangerOverride(callInfo, IPAddress);
            return callInfo;
        }

        [NonAction]
        partial void ServiceSMSOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ServiceSMS()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ServiceSMS);
            ServiceSMSOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void getInfoAccountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult getInfoAccount()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.getInfoAccount);
            getInfoAccountOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SendSimpleSMS2Override(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.SMSViewModel.SndSMSViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendSimpleSMS2(eShop.WebApplication.DomainClasses.SMSViewModel.SndSMSViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendSimpleSMS2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SendSimpleSMS2Override(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetUnReadSMSOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetUnReadSMS()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetUnReadSMS);
            GetUnReadSMSOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void dataSMSInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page);

        [NonAction]
        public override System.Web.Mvc.ActionResult dataSMSInfo(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.dataSMSInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            dataSMSInfoOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void GetReadSMSOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetReadSMS()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetReadSMS);
            GetReadSMSOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void dataSMSInfoReadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page);

        [NonAction]
        public override System.Web.Mvc.ActionResult dataSMSInfoRead(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.dataSMSInfoRead);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            dataSMSInfoReadOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void SchedulerListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SchedulerList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SchedulerList);
            SchedulerListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetIPForAutoCompleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string term);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIPForAutoComplete(string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIPForAutoComplete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            GetIPForAutoCompleteOverride(callInfo, term);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
