// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace WebApplication.Areas.admin.Controllers
{
    public partial class ContactUsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ContactUsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ChageStatusRead()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChageStatusRead);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteMessage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteMessage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AnswerContact()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AnswerContact);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResultAnswerContact()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResultAnswerContact);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ContactUsController Actions { get { return MVC.admin.ContactUs; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ContactUs";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ContactUs";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string DataContactUs = "DataContactUs";
            public readonly string SerachContactUs = "SerachContactUs";
            public readonly string ChageStatusRead = "ChageStatusRead";
            public readonly string DeleteMessage = "DeleteMessage";
            public readonly string AnswerContact = "AnswerContact";
            public readonly string ResultAnswerContact = "ResultAnswerContact";
            public readonly string GetFiveContactUsLat = "GetFiveContactUsLat";
            public readonly string GetCountMessageNotRead = "GetCountMessageNotRead";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string DataContactUs = "DataContactUs";
            public const string SerachContactUs = "SerachContactUs";
            public const string ChageStatusRead = "ChageStatusRead";
            public const string DeleteMessage = "DeleteMessage";
            public const string AnswerContact = "AnswerContact";
            public const string ResultAnswerContact = "ResultAnswerContact";
            public const string GetFiveContactUsLat = "GetFiveContactUsLat";
            public const string GetCountMessageNotRead = "GetCountMessageNotRead";
        }


        static readonly ActionParamsClass_DataContactUs s_params_DataContactUs = new ActionParamsClass_DataContactUs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DataContactUs DataContactUsParams { get { return s_params_DataContactUs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DataContactUs
        {
            public readonly string term = "term";
            public readonly string count = "count";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_ChageStatusRead s_params_ChageStatusRead = new ActionParamsClass_ChageStatusRead();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChageStatusRead ChageStatusReadParams { get { return s_params_ChageStatusRead; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChageStatusRead
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteMessage s_params_DeleteMessage = new ActionParamsClass_DeleteMessage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteMessage DeleteMessageParams { get { return s_params_DeleteMessage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteMessage
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AnswerContact s_params_AnswerContact = new ActionParamsClass_AnswerContact();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AnswerContact AnswerContactParams { get { return s_params_AnswerContact; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AnswerContact
        {
            public readonly string user_Id = "user_Id";
            public readonly string contact_Id = "contact_Id";
            public readonly string flName = "flName";
        }
        static readonly ActionParamsClass_ResultAnswerContact s_params_ResultAnswerContact = new ActionParamsClass_ResultAnswerContact();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResultAnswerContact ResultAnswerContactParams { get { return s_params_ResultAnswerContact; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResultAnswerContact
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AnswerContact = "_AnswerContact";
                public readonly string _DataFiveLast = "_DataFiveLast";
                public readonly string _DataTableContactUs = "_DataTableContactUs";
                public readonly string _NoDataFiveLast = "_NoDataFiveLast";
                public readonly string _SearchContactUs = "_SearchContactUs";
                public readonly string _SolidHeaderContactUs = "_SolidHeaderContactUs";
                public readonly string Index = "Index";
            }
            public readonly string _AnswerContact = "~/Areas/admin/Views/ContactUs/_AnswerContact.cshtml";
            public readonly string _DataFiveLast = "~/Areas/admin/Views/ContactUs/_DataFiveLast.cshtml";
            public readonly string _DataTableContactUs = "~/Areas/admin/Views/ContactUs/_DataTableContactUs.cshtml";
            public readonly string _NoDataFiveLast = "~/Areas/admin/Views/ContactUs/_NoDataFiveLast.cshtml";
            public readonly string _SearchContactUs = "~/Areas/admin/Views/ContactUs/_SearchContactUs.cshtml";
            public readonly string _SolidHeaderContactUs = "~/Areas/admin/Views/ContactUs/_SolidHeaderContactUs.cshtml";
            public readonly string Index = "~/Areas/admin/Views/ContactUs/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ContactUsController : WebApplication.Areas.admin.Controllers.ContactUsController
    {
        public T4MVC_ContactUsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DataContactUsOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string term, int count, int page);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DataContactUs(string term, int count, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DataContactUs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            DataContactUsOverride(callInfo, term, count, page);
            return callInfo;
        }

        [NonAction]
        partial void SerachContactUsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SerachContactUs()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SerachContactUs);
            SerachContactUsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChageStatusReadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChageStatusRead(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChageStatusRead);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ChageStatusReadOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteMessageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteMessage(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteMessage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteMessageOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AnswerContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int user_Id, int contact_Id, string flName);

        [NonAction]
        public override System.Web.Mvc.ActionResult AnswerContact(int user_Id, int contact_Id, string flName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AnswerContact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "user_Id", user_Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "contact_Id", contact_Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "flName", flName);
            AnswerContactOverride(callInfo, user_Id, contact_Id, flName);
            return callInfo;
        }

        [NonAction]
        partial void ResultAnswerContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.ViewModelClasses.AnswerContactViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResultAnswerContact(eShop.WebApplication.DomainClasses.ViewModelClasses.AnswerContactViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResultAnswerContact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ResultAnswerContactOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void GetFiveContactUsLatOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetFiveContactUsLat()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFiveContactUsLat);
            GetFiveContactUsLatOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetCountMessageNotReadOverride(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult GetCountMessageNotRead()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.GetCountMessageNotRead);
            GetCountMessageNotReadOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
