// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace WebApplication.Areas.admin.Controllers
{
    public partial class CommentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CommentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PagedIndex()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PagedIndex);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Post()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Post);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResponseComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResponseComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllCommentPerProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllCommentPerProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ChangeStatusRead()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeStatusRead);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SendComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendComment);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CommentController Actions { get { return MVC.admin.Comment; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Comment";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Comment";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string PagedIndex = "PagedIndex";
            public readonly string Post = "Post";
            public readonly string ResponseComment = "ResponseComment";
            public readonly string UpdateComment = "UpdateComment";
            public readonly string GetAllCommentPerProduct = "GetAllCommentPerProduct";
            public readonly string ChangeStatusRead = "ChangeStatusRead";
            public readonly string DeleteComment = "DeleteComment";
            public readonly string SendComment = "SendComment";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string PagedIndex = "PagedIndex";
            public const string Post = "Post";
            public const string ResponseComment = "ResponseComment";
            public const string UpdateComment = "UpdateComment";
            public const string GetAllCommentPerProduct = "GetAllCommentPerProduct";
            public const string ChangeStatusRead = "ChangeStatusRead";
            public const string DeleteComment = "DeleteComment";
            public const string SendComment = "SendComment";
        }


        static readonly ActionParamsClass_PagedIndex s_params_PagedIndex = new ActionParamsClass_PagedIndex();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PagedIndex PagedIndexParams { get { return s_params_PagedIndex; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PagedIndex
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Post s_params_Post = new ActionParamsClass_Post();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Post PostParams { get { return s_params_Post; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Post
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ResponseComment s_params_ResponseComment = new ActionParamsClass_ResponseComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResponseComment ResponseCommentParams { get { return s_params_ResponseComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResponseComment
        {
            public readonly string Id = "Id";
            public readonly string comment = "comment";
        }
        static readonly ActionParamsClass_UpdateComment s_params_UpdateComment = new ActionParamsClass_UpdateComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateComment UpdateCommentParams { get { return s_params_UpdateComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateComment
        {
            public readonly string Id = "Id";
            public readonly string comment = "comment";
        }
        static readonly ActionParamsClass_GetAllCommentPerProduct s_params_GetAllCommentPerProduct = new ActionParamsClass_GetAllCommentPerProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllCommentPerProduct GetAllCommentPerProductParams { get { return s_params_GetAllCommentPerProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllCommentPerProduct
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_ChangeStatusRead s_params_ChangeStatusRead = new ActionParamsClass_ChangeStatusRead();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeStatusRead ChangeStatusReadParams { get { return s_params_ChangeStatusRead; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeStatusRead
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_DeleteComment s_params_DeleteComment = new ActionParamsClass_DeleteComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteComment DeleteCommentParams { get { return s_params_DeleteComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteComment
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_SendComment s_params_SendComment = new ActionParamsClass_SendComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendComment SendCommentParams { get { return s_params_SendComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendComment
        {
            public readonly string Id = "Id";
            public readonly string ExplainComment = "ExplainComment";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _DataComment = "_DataComment";
                public readonly string _DataCommentPerProduct = "_DataCommentPerProduct";
                public readonly string Index = "Index";
                public readonly string ResponseComment = "ResponseComment";
                public readonly string UpdateComment = "UpdateComment";
            }
            public readonly string _DataComment = "~/Areas/admin/Views/Comment/_DataComment.cshtml";
            public readonly string _DataCommentPerProduct = "~/Areas/admin/Views/Comment/_DataCommentPerProduct.cshtml";
            public readonly string Index = "~/Areas/admin/Views/Comment/Index.cshtml";
            public readonly string ResponseComment = "~/Areas/admin/Views/Comment/ResponseComment.cshtml";
            public readonly string UpdateComment = "~/Areas/admin/Views/Comment/UpdateComment.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CommentController : WebApplication.Areas.admin.Controllers.CommentController
    {
        public T4MVC_CommentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PagedIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? page);

        [NonAction]
        public override System.Web.Mvc.ActionResult PagedIndex(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PagedIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            PagedIndexOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void PostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Post(int? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Post);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PostOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ResponseCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResponseComment(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResponseComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ResponseCommentOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void ResponseCommentOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, eShop.WebApplication.DomainClasses.AppClasses.Comment comment);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ResponseComment(eShop.WebApplication.DomainClasses.AppClasses.Comment comment)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ResponseComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "comment", comment);
            ResponseCommentOverride(callInfo, comment);
            return callInfo;
        }

        [NonAction]
        partial void UpdateCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateComment(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            UpdateCommentOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void UpdateCommentOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, eShop.WebApplication.DomainClasses.AppClasses.Comment comment);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult UpdateComment(eShop.WebApplication.DomainClasses.AppClasses.Comment comment)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.UpdateComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "comment", comment);
            UpdateCommentOverride(callInfo, comment);
            return callInfo;
        }

        [NonAction]
        partial void GetAllCommentPerProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllCommentPerProduct(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllCommentPerProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            GetAllCommentPerProductOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void ChangeStatusReadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangeStatusRead(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeStatusRead);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ChangeStatusReadOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteComment(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteCommentOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void SendCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id, string ExplainComment);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendComment(int Id, string ExplainComment)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ExplainComment", ExplainComment);
            SendCommentOverride(callInfo, Id, ExplainComment);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
