// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace WebApplication.Areas.admin.Controllers
{
    public partial class SaleController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SaleController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DetailsSale()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailsSale);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ConfirmSale()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmSale);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResultConfirmSale()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResultConfirmSale);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SendTrackingNumber()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendTrackingNumber);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResultSendTrackingNumber()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResultSendTrackingNumber);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult DeleteSale()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DeleteSale);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SaleController Actions { get { return MVC.admin.Sale; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Sale";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Sale";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ChartSaleSevenDayAgo = "ChartSaleSevenDayAgo";
            public readonly string DataSale = "DataSale";
            public readonly string SearchSale = "SearchSale";
            public readonly string DetailsSale = "DetailsSale";
            public readonly string ConfirmSale = "ConfirmSale";
            public readonly string ResultConfirmSale = "ResultConfirmSale";
            public readonly string SendTrackingNumber = "SendTrackingNumber";
            public readonly string ResultSendTrackingNumber = "ResultSendTrackingNumber";
            public readonly string DeleteSale = "DeleteSale";
            public readonly string GetCountNotConfirmed = "GetCountNotConfirmed";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ChartSaleSevenDayAgo = "ChartSaleSevenDayAgo";
            public const string DataSale = "DataSale";
            public const string SearchSale = "SearchSale";
            public const string DetailsSale = "DetailsSale";
            public const string ConfirmSale = "ConfirmSale";
            public const string ResultConfirmSale = "ResultConfirmSale";
            public const string SendTrackingNumber = "SendTrackingNumber";
            public const string ResultSendTrackingNumber = "ResultSendTrackingNumber";
            public const string DeleteSale = "DeleteSale";
            public const string GetCountNotConfirmed = "GetCountNotConfirmed";
        }


        static readonly ActionParamsClass_DataSale s_params_DataSale = new ActionParamsClass_DataSale();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DataSale DataSaleParams { get { return s_params_DataSale; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DataSale
        {
            public readonly string term = "term";
            public readonly string count = "count";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_DetailsSale s_params_DetailsSale = new ActionParamsClass_DetailsSale();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailsSale DetailsSaleParams { get { return s_params_DetailsSale; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailsSale
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_ConfirmSale s_params_ConfirmSale = new ActionParamsClass_ConfirmSale();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmSale ConfirmSaleParams { get { return s_params_ConfirmSale; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmSale
        {
            public readonly string User_Id = "User_Id";
            public readonly string Sale_Id = "Sale_Id";
        }
        static readonly ActionParamsClass_ResultConfirmSale s_params_ResultConfirmSale = new ActionParamsClass_ResultConfirmSale();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResultConfirmSale ResultConfirmSaleParams { get { return s_params_ResultConfirmSale; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResultConfirmSale
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SendTrackingNumber s_params_SendTrackingNumber = new ActionParamsClass_SendTrackingNumber();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendTrackingNumber SendTrackingNumberParams { get { return s_params_SendTrackingNumber; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendTrackingNumber
        {
            public readonly string User_Id = "User_Id";
            public readonly string Sale_Id = "Sale_Id";
        }
        static readonly ActionParamsClass_ResultSendTrackingNumber s_params_ResultSendTrackingNumber = new ActionParamsClass_ResultSendTrackingNumber();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResultSendTrackingNumber ResultSendTrackingNumberParams { get { return s_params_ResultSendTrackingNumber; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResultSendTrackingNumber
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteSale s_params_DeleteSale = new ActionParamsClass_DeleteSale();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteSale DeleteSaleParams { get { return s_params_DeleteSale; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteSale
        {
            public readonly string Id = "Id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ChartSaleSevenDayAgo = "_ChartSaleSevenDayAgo";
                public readonly string _ConfirmSale = "_ConfirmSale";
                public readonly string _DataTableSale = "_DataTableSale";
                public readonly string _Scheduler = "_Scheduler";
                public readonly string _SearchSale = "_SearchSale";
                public readonly string _SendTrackingNumber = "_SendTrackingNumber";
                public readonly string _SolidHeaderSale = "_SolidHeaderSale";
                public readonly string DetailsSale = "DetailsSale";
                public readonly string Index = "Index";
            }
            public readonly string _ChartSaleSevenDayAgo = "~/Areas/admin/Views/Sale/_ChartSaleSevenDayAgo.cshtml";
            public readonly string _ConfirmSale = "~/Areas/admin/Views/Sale/_ConfirmSale.cshtml";
            public readonly string _DataTableSale = "~/Areas/admin/Views/Sale/_DataTableSale.cshtml";
            public readonly string _Scheduler = "~/Areas/admin/Views/Sale/_Scheduler.cshtml";
            public readonly string _SearchSale = "~/Areas/admin/Views/Sale/_SearchSale.cshtml";
            public readonly string _SendTrackingNumber = "~/Areas/admin/Views/Sale/_SendTrackingNumber.cshtml";
            public readonly string _SolidHeaderSale = "~/Areas/admin/Views/Sale/_SolidHeaderSale.cshtml";
            public readonly string DetailsSale = "~/Areas/admin/Views/Sale/DetailsSale.cshtml";
            public readonly string Index = "~/Areas/admin/Views/Sale/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SaleController : WebApplication.Areas.admin.Controllers.SaleController
    {
        public T4MVC_SaleController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChartSaleSevenDayAgoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChartSaleSevenDayAgo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChartSaleSevenDayAgo);
            ChartSaleSevenDayAgoOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DataSaleOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string term, int count, int page);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DataSale(string term, int count, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DataSale);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            DataSaleOverride(callInfo, term, count, page);
            return callInfo;
        }

        [NonAction]
        partial void SearchSaleOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult SearchSale()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.SearchSale);
            SearchSaleOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailsSaleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetailsSale(int? Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailsSale);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DetailsSaleOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmSaleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int User_Id, int Sale_Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ConfirmSale(int User_Id, int Sale_Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmSale);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "User_Id", User_Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Sale_Id", Sale_Id);
            ConfirmSaleOverride(callInfo, User_Id, Sale_Id);
            return callInfo;
        }

        [NonAction]
        partial void ResultConfirmSaleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.ViewModelClasses.ConfirmSaleViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResultConfirmSale(eShop.WebApplication.DomainClasses.ViewModelClasses.ConfirmSaleViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResultConfirmSale);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ResultConfirmSaleOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void SendTrackingNumberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int User_Id, int Sale_Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendTrackingNumber(int User_Id, int Sale_Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendTrackingNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "User_Id", User_Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Sale_Id", Sale_Id);
            SendTrackingNumberOverride(callInfo, User_Id, Sale_Id);
            return callInfo;
        }

        [NonAction]
        partial void ResultSendTrackingNumberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, eShop.WebApplication.DomainClasses.ViewModelClasses.ConfirmSaleViewModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResultSendTrackingNumber(eShop.WebApplication.DomainClasses.ViewModelClasses.ConfirmSaleViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResultSendTrackingNumber);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ResultSendTrackingNumberOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void DeleteSaleOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult DeleteSale(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.DeleteSale);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteSaleOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void GetCountNotConfirmedOverride(T4MVC_System_Web_Mvc_ContentResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ContentResult GetCountNotConfirmed()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.GetCountNotConfirmed);
            GetCountNotConfirmedOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
